# Generated by Django 5.0.14 on 2026-07-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_merge_20260629_1459'),
        ('accounting', '0028_vouchercreditnoteinvoicedetails_gst_registered'),
    ]

    operations = [
    ]
