# Generated by Django 5.0.14 on 2026-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_merge_20260709_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchercreditnoteinvoicedetails',
            name='gst_registered',
        ),
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='amendment_filed',
            field=models.BooleanField(default=False, help_text='True if the amendment itself has been GST filed'),
        ),
    ]
