# Generated by Django 5.0.14 on 2026-07-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_remove_vouchercreditnoteinvoicedetails_gst_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercreditnoteinvoicedetails',
            name='gst_registered',
            field=models.CharField(blank=True, default='', help_text="'Yes' if this voucher has been filed in GST, empty otherwise", max_length=3),
        ),
    ]
