# Generated by Django 5.0.14 on 2026-07-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_vouchercreditnoteinvoicedetails_gst_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercreditnoteinvoicedetails',
            name='amendment_date',
            field=models.DateField(blank=True, help_text='Date when this voucher was amended after being GST filed', null=True),
        ),
        migrations.AddField(
            model_name='vouchercreditnoteinvoicedetails',
            name='amendment_filed',
            field=models.BooleanField(default=False, help_text='True if the amendment itself has been GST filed'),
        ),
        migrations.AddField(
            model_name='vouchercreditnoteinvoicedetails',
            name='original_voucher_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the original voucher before amendment', null=True),
        ),
    ]
