# Generated by Django 5.0.14 on 2026-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_vouchercreditnoteinvoicedetails_amendment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='is_ecommerce_operator',
            field=models.BooleanField(default=False, help_text='True if the tenant is acting as an E-Commerce Operator (ECO) under Sec 9(5)'),
        ),
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='third_party_supplier_gstin',
            field=models.CharField(blank=True, help_text='GSTIN of the third-party supplier. If blank, supplier is URP.', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='third_party_supplier_name',
            field=models.CharField(blank=True, help_text='Name of the third-party supplier', max_length=255, null=True),
        ),
    ]
