# Generated by Django 5.0.14 on 2026-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_vouchersalesinvoicedetails_is_ecommerce_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceallocation',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST Rate (e.g. 18.00) for Advance Tax (AT) reporting', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST Rate (e.g. 18.00) for Advance Tax (AT) reporting', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST Rate (e.g. 18.00) for Advance Tax (AT) reporting', max_digits=5, null=True),
        ),
    ]
