# Generated by Django 5.0.14 on 2026-07-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_advanceallocation_gst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceallocation',
            name='gst_registered',
            field=models.CharField(blank=True, default='', help_text="'Yes' if this advance has been filed in GST, empty otherwise", max_length=3),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='gst_registered',
            field=models.CharField(blank=True, default='', help_text="'Yes' if this advance has been filed in GST, empty otherwise", max_length=3),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='gst_registered',
            field=models.CharField(blank=True, default='', help_text="'Yes' if this advance has been filed in GST, empty otherwise", max_length=3),
        ),
    ]
