# Generated by Django 5.0.14 on 2026-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_advanceallocation_gst_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceallocation',
            name='amendment_date',
            field=models.DateField(blank=True, help_text='Date when the advance was amended', null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='original_voucher_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the original filed AT values', null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='amendment_date',
            field=models.DateField(blank=True, help_text='Date when the advance was amended', null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='original_voucher_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the original filed AT values', null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='amendment_date',
            field=models.DateField(blank=True, help_text='Date when the advance was amended', null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='original_voucher_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the original filed AT values', null=True),
        ),
    ]
