# Generated by Django 5.0.14 on 2026-07-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_advanceallocation_amendment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceallocation',
            name='amendment_filed',
            field=models.BooleanField(default=False, help_text='True once this ATA amendment has been filed in GST'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='amendment_filed',
            field=models.BooleanField(default=False, help_text='True once this ATA amendment has been filed in GST'),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='amendment_filed',
            field=models.BooleanField(default=False, help_text='True once this ATA amendment has been filed in GST'),
        ),
    ]
