# Generated by Django 5.0.14 on 2026-07-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_voucherpurchaseitem_discount_amount_and_more'),
        ('accounting', '0037_add_amendment_filed_to_allocation'),
    ]

    operations = [
    ]
