# Generated by Django 5.0.14 on 2026-07-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_merge_20260717_1146'),
        ('accounting', '0038_merge_20260717_1234'),
    ]

    operations = [
    ]
