# Generated by Django 5.0.14 on 2026-07-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_merge_20260720_1342'),
        ('accounting', '0039_merge_20260723_1702'),
    ]

    operations = [
    ]
