# Generated by Django 5.0.14 on 2026-08-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_merge_20260725_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterledger',
            unique_together={('name', 'tenant_id')},
        ),
    ]
