# Generated by Django 5.0.14 on 2026-07-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0025_add_ocr_sprint3_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicache',
            name='key_hash',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
