# Generated by Django 5.0.14 on 2026-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0004_alter_customermaster_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermasterlongtermcontractbasicdetail',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Is the contract paused'),
        ),
    ]
