# Generated by Django 5.0.14 on 2026-08-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending_purchases', '0002_add_status_columns_to_ocr_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpurchase',
            name='company_match_decision',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pendingpurchase',
            name='company_match_detected',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
