# Generated by Django 5.0.14 on 2026-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reconciliation', '0002_gstjobstatus_validationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTElectronicLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_balance_igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_balance_cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_balance_sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('liability_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gst_electronic_ledgers',
            },
        ),
    ]
