# Generated by Django 5.0.14 on 2026-07-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reconciliation', '0003_gstelectronicledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstr3breport',
            name='arn_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gstr3breport',
            name='filed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstr3breport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FILED', 'Filed')], default='DRAFT', max_length=20),
        ),
    ]
