# Generated by Django 5.0.14 on 2026-07-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reconciliation', '0004_gstr3breport_arn_number_gstr3breport_filed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTLateFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_type', models.CharField(choices=[('GSTR3B', 'GSTR-3B'), ('GSTR1', 'GSTR-1')], default='GSTR3B', max_length=10)),
                ('period_month', models.CharField(max_length=20)),
                ('period_year', models.CharField(max_length=10)),
                ('due_date', models.DateField()),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('days_late', models.IntegerField(default=0)),
                ('is_nil_return', models.BooleanField(default=False)),
                ('cgst_late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='PENDING', max_length=10)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gst_late_fees',
                'unique_together': {('return_type', 'period_month', 'period_year')},
            },
        ),
    ]
