# Generated by Django 5.0.14 on 2026-08-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reconciliation', '0005_add_gst_late_fee_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gstr3breport',
            unique_together={('period_month', 'period_year')},
        ),
        migrations.AlterUniqueTogether(
            name='itcsummary',
            unique_together={('period_month', 'period_year')},
        ),
    ]
