# Generated by Django 5.0.14 on 2026-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_inventory_m_tenant__feb7a0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='opening_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='opening_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
