# Generated by Django 5.0.14 on 2026-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notereminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='KikiAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('user_question', models.TextField()),
                ('domain_identified', models.CharField(blank=True, max_length=100, null=True)),
                ('reasoning_steps', models.JSONField(blank=True, default=list)),
                ('executed_queries', models.JSONField(blank=True, default=list)),
                ('intents_emitted', models.JSONField(blank=True, default=list)),
                ('evidence_summary', models.JSONField(blank=True, default=dict)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('final_answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
            ],
            options={
                'db_table': 'kiki_agent_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
