# Generated by Django 5.0.14 on 2026-08-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_kikiauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGActiveIndex',
            fields=[
                ('active_index_version', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('corpus_version', models.CharField(max_length=64)),
                ('embedding_model', models.CharField(max_length=128)),
                ('embedding_dimension', models.IntegerField()),
                ('distance_metric', models.CharField(max_length=32)),
                ('normalized', models.BooleanField()),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rag_active_index',
            },
        ),
        migrations.CreateModel(
            name='RAGReindexJob',
            fields=[
                ('job_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REINDEX_IDLE', 'Idle'), ('REINDEX_REQUIRED', 'Required'), ('REINDEX_SCHEDULED', 'Scheduled'), ('REINDEX_RUNNING', 'Running'), ('REINDEX_VALIDATING', 'Validating'), ('REINDEX_READY_TO_PROMOTE', 'Ready to Promote'), ('REINDEX_PROMOTED', 'Promoted'), ('REINDEX_FAILED', 'Failed'), ('REINDEX_ROLLED_BACK', 'Rolled Back')], default='REINDEX_IDLE', max_length=32)),
                ('trigger_type', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('source_index_version', models.CharField(max_length=64)),
                ('target_index_version', models.CharField(max_length=64)),
                ('source_corpus_version', models.CharField(max_length=64)),
                ('target_corpus_version', models.CharField(max_length=64)),
                ('embedding_model', models.CharField(max_length=128)),
                ('embedding_dimension', models.IntegerField()),
                ('distance_metric', models.CharField(max_length=32)),
                ('normalized', models.BooleanField()),
                ('progress', models.FloatField(default=0.0)),
                ('documents_total', models.IntegerField(default=0)),
                ('documents_processed', models.IntegerField(default=0)),
                ('chunks_total', models.IntegerField(default=0)),
                ('chunks_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rag_reindex_jobs',
            },
        ),
    ]
